### ISSUE TITLE
Exported SVG does not behave well

### ISSUE THREAD

**Issue by leptoceratops** [akulmehta/GlycoGlyphPublic#25]
Firstly, thank you for developing this very useful tool for representing glycans using the SNFG. I would like to bring to your attention the problems I had regarding exporting svg files. The svg files exported by GlycoGlyph (web app) can be viewed and edited in Inkscape but the selection rectangle does not match with the object (see image below).
<img width="401" alt="inkscape_group" src="https://user-images.githubusercontent.com/43407469/100540094-114e5800-3233-11eb-98d8-cf6a7d920da1.png">

**Comment by akulmehta** [comment]
Hi @leptoceratops, thank you for your kind words. This issue is because of how Inkscape performs the selection and not so much an issue of GlycoGlyph.

The SVG file is layered into several groups. There is a main glycan group called `glycang` (which seems to be what is showing up in the rectangle in the image above), under which there are sub groups for each node and paths for the linkages. How the group appears when selected depends on the tool you use. It is different in browsers, and editors.

e.g. in firefox 
![image](https://user-images.githubusercontent.com/42812604/101080328-aa080f00-3576-11eb-93a7-59162433ce64.png)

while in Adobe Illustrator no box is shown.

You should be able to select specific elements on the glycan in inkscape once you go inside the group.

To help you with inkscape, a larger glycan shown here has a bigger rectangle for the `glycang`
![image](https://user-images.githubusercontent.com/42812604/101081249-d2dcd400-3577-11eb-819d-0c1aeb617ec9.png)

If you double click on any of the nodes using the "Select and Transform Objects", you enter this group and you can now select each node, with their relative linkage texts (again as a group). 
![image](https://user-images.githubusercontent.com/42812604/101081291-dd976900-3577-11eb-81be-373049c1280e.png)

You can edit this group as an example I moved it below:
![image](https://user-images.githubusercontent.com/42812604/101081391-fe5fbe80-3577-11eb-8bda-753cc0995a2a.png)

or you can enter this group again by double clicking and making specific selections.

**Alternatively, in Inkscape you can directly edit the element you select by holding down the Ctrl+click on the node/text/linkage you want to edit.**
 
I hope this helps.

**Comment by leptoceratops** [comment]
Thank you for your message. I tried the Ctrl+click and I can select the #glc layer for example and I tried to place it in the center of the #glycang layer, but this is not possible. The reason that I would like to do that is so that if I want to import the svg file to wikipedia the #glc layer is not in the center. Shall I attach a snapshot from mediawiki?

**Comment by akulmehta** [comment]
Please attach the snapshot, and if possible provide a link to the file or attach it, so that I can inspect the contents.

**Comment by leptoceratops** [comment]
I am attaching a png screenshot of the svg file in inkscape (github prevents me from uploading the svg file) 
<img width="319" alt="quinovose_in_inkscape" src="https://user-images.githubusercontent.com/43407469/101525129-8d634100-3993-11eb-9e97-25ef4f7c6931.png">
and a screenshot of when I upload it on a mediawiki <img width="504" alt="quinovose_uploaded _in_wiki" src="https://user-images.githubusercontent.com/43407469/101525135-8e946e00-3993-11eb-914c-28d38a48fa98.png">. 
The png thumbnail created by the mediawiki (using Imagemagick I think) shows the glyph off centered.

**Comment by akulmehta** [comment]
Could you share the link to the page so that I can inspect if there is something that can be done?

**Comment by leptoceratops** [comment]
Hi Akul,

If I use this reply address would it work?

K

**Comment by akulmehta** [comment]
Do you have access to a mediawiki where I can test uploading the svg generated from GlycoGlyph?

**Comment by leptoceratops** [comment]
The snapshot I posted above is from a local wiki. The only publicly accessible wiki I can think of is wikipedia.
I tried it on wikipedia and it works now so the problem probably lies in the fact that I am using `convert` to create png thumbnails in the local wiki.

**Comment by akulmehta** [comment]
I see. The Imagemagick step is probably where I would look too. Most likely, it is cropping the svg from the top left, therefore cutting the image in some way. If there is nothing else I can do at the moment I will go ahead and close this issue.

**Comment by leptoceratops** [comment]
Could you try converting it with ImageMagick please?
[Quinovose.txt](https://github.com/akulmehta/GlycoGlyphPublic/files/5662149/Quinovose.txt)
I have changed the extension from .svg to .txt

**Comment by akulmehta** [comment]
Unfortunately I am not familiar with it. You may need to ask someone else for help with it.

**Comment by leptoceratops** [comment]
I just wanted to let you know that I have switched the wiki's $wgSVGConverter from `convert` (ImageMagick) to `rsvg-convert` (rsvg) and the error has gone away!

**Comment by akulmehta** [comment]
Interesting... thanks for letting us know here so that it may help others as well.
